# Generated by Django 5.0.6 on 2024-07-26 02:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentm',
            managers=[
                ('adarsh', django.db.models.manager.Manager()),
            ],
        ),
    ]
